# Generated by Django 5.1.3 on 2025-08-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjiraApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('unit_code', models.CharField(max_length=10)),
                ('unit_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('day', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=50)),
            ],
        ),
    ]
