# Generated by Django 5.1.3 on 2025-08-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjiraApp', '0002_timetableentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='day',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='unit_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='unit_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
