# Generated by Django 5.1.3 on 2025-08-22 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjiraApp', '0003_alter_timetableentry_day_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['day', 'time'], name='AjiraApp_ti_day_cfebc1_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['course_code'], name='AjiraApp_ti_course__22ab95_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['room'], name='AjiraApp_ti_room_b0921c_idx'),
        ),
    ]
