# Generated by Django 5.1.3 on 2025-08-23 10:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjiraApp', '0008_memo_created_at_alter_memo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
