# Generated by Django 5.1.3 on 2025-08-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjiraApp', '0013_music_politics_religion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='music',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='music_files/'),
        ),
        migrations.AddField(
            model_name='politics',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='politics_files/'),
        ),
        migrations.AddField(
            model_name='religion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='religion_files/'),
        ),
    ]
