# Generated by Django 5.1.3 on 2025-08-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AjiraApp', '0015_confession'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='mega_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='mega_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memo',
            name='mega_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='mega_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='mega_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='politics',
            name='mega_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='mega_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='religion',
            name='mega_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
