# Generated by Django 5.1.3 on 2025-08-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AjiraApp', '0016_advertisement_mega_link_hostel_mega_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='mega_link',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='mega_link',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='mega_link',
        ),
        migrations.RemoveField(
            model_name='music',
            name='mega_link',
        ),
        migrations.RemoveField(
            model_name='news',
            name='mega_link',
        ),
        migrations.RemoveField(
            model_name='politics',
            name='mega_link',
        ),
        migrations.RemoveField(
            model_name='reel',
            name='mega_link',
        ),
        migrations.RemoveField(
            model_name='religion',
            name='mega_link',
        ),
    ]
